In [1]:
import numpy as np

ARRAY OPERATIONS

1.Arithmetic Operation

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [5]:
#add corresponding element
arr1=a1+a2 
arr1                   #the size of both array need to be same

array([ 7,  9, 11, 13, 15])

In [6]:
arr2=a1*a2
arr2

array([ 6, 14, 24, 36, 50])

floor division,subtraction,power these operations also performed

In [7]:
#broadcasting
arr=np.array([10,20,30,40,50])
arr+10

array([20, 30, 40, 50, 60])

Deep and Shallow copy

In [8]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice=slice*10
slice                                               #shallow copy

array([10, 20, 30, 40, 50])

In [10]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b=a             #deep copy
b[0]=99
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
c=a.copy()      #shallow copy
c[0]=8
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operation