In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS 

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
#Indexing in vector is same as in list
arr[6]

np.int64(17)

In [4]:
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[::2]

array([11, 13, 15, 17, 19])

NUMPY INDEXING AND SLICING OF MATRIX


In [10]:
arr=np.arange(1,31)
arr=arr.reshape(6,5)

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [15]:
arr[5,4]

np.int64(30)

In [16]:
#need 2,3
#     7,8
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [17]:
#19,20
#24,25
#29,30
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
#selecting single column
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [21]:
arr=np.arange(1,21)

In [ ]:
bool_index=arr%2==0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [23]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])