In [109]:
import numpy as np

Valid Sodoku

In [110]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [111]:
b=np.sum(s,axis=0)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [112]:
a=np.sum(s,axis=1)
a==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [113]:
for j in range(3):
    for i in range(0,9,3):
        print(s[i:i+3,i:i+3])
        

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [114]:
for j in range(3):
    for i in range(0,9,3):
        x=np.sum(s[i:i+3,i:i+3])
        x==45

General Questions

In [115]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [116]:
#Get the shape of the matrix.
np.shape(data)

(5, 3)

In [117]:
#Find the average age of students.
age=data[:,0]
averageAge=age.sum()/5
averageAge=np.mean(data[:,0])
print("Average Age of student is :: ",averageAge)

Average Age of student is ::  18.4


In [118]:
#Extract Math marks of all students.
mathMarks=data[:,1]
mathMarks

array([85, 92, 76, 65, 90])

In [119]:
#Find the highest Science mark.
ScienceMarks=data[:,2]
np.max(ScienceMarks)

np.int64(95)

In [120]:
#Get details of the student who scored more than 90 in Math.
# mathMarks=data[:,1]>1
# for i in range(len(mathMarks)):
#     if(mathMarks[i]==90):
#         print("Student Details :: ",data[i])
mathMarks=data[:,1]>90
data[mathMarks]

array([[19, 92, 88]])

In [121]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data



array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [122]:
#Find how many students are younger than 19.
boolean_array=data[:,0]<19
len(data[boolean_array])

3

In [123]:
#Calculate the average marks in each subject (column-wise mean).
columnMean=data[:,1:].mean(axis=0)
columnMean


array([86.6, 83.2])

In [124]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [125]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])