In [4]:
import numpy as np

Basic Array Creation


In [8]:
arr=np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([5,6,1,3.4])
a


array(['hello', '5', '6', '1', '3.4'], dtype='<U32')

In [15]:
b=np.array(["hello",5,6,1,3.4])

b


array(['hello', '5', '6', '1', '3.4'], dtype='<U32')

VECTORS VS MATRIX

VECTOR::One dimensional array
MATRIX::N dimensional array

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]   #matrix
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [18]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ar=np.zeros((6,6))
ar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
ar=np.ones((6,6))
ar

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

RANDOM GENERATION FUNCTION

In [24]:
np.random.rand(10)

array([0.67403466, 0.65774615, 0.4944507 , 0.02199956, 0.42870792,
       0.99958764, 0.38262343, 0.70242714, 0.14472184, 0.27592415])

In [26]:
np.random.randn(6)


array([ 0.87747665, -0.78716678, -0.17674591, -2.58324948,  0.83139311,
       -0.46087116])

Array Attributes

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.shape

(3, 3)

In [30]:
arr.size

9

In [31]:
arr.dtype

dtype('int64')

Array Methods

In [32]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr,axis=0) #axis=0  column   axis=1 row

array([12, 15, 18])

In [39]:
np.std(arr,axis=0)
np.std(arr)

np.float64(2.581988897471611)

In [40]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
arr.reshape(10,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])